env = SDL_VIDEODRIVER,wayland

general {
	gaps_in = 4
	gaps_out = 8
	layout = dwindle
	resize_on_border = true
	border_size = 2
	col.active_border = rgba(ff0000ff) rgba(ff7f00ff) rgba(ffff00ff) rgba(00ff00ff) rgba(0000ffff) rgba(8B00ffff) 60deg
	col.inactive_border = rgba(000000bb)
}

decoration {
	shadow {
		enabled = true
		range = 30
		render_power = 3
		color = 0x66000000
	}

	inactive_opacity = 0.40
	active_opacity = 0.50
	fullscreen_opacity = 1.00
	rounding = 10
	
	blur {
		enabled = true
		size = 6
		noise = 0.00
		passes = 2
		new_optimizations = true
		xray = true
		vibrancy_darkness = 0.40
		popups = true
		popups_ignorealpha = 0.20
		ignore_opacity = true
	}
}

animations {
	enabled = true
	first_launch_animation = true
}
