exec-once = systemctl --user import-environment WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_ID XDG_SESSION_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP

exec-once = uwsm app -- qs
exec-once = uwsm app -- nm-applet --indicator
exec-once = uwsm app -- blueman-applet
exec-once = livepaper --restore
exec-once = uwsm app -- livepaper

exec-once = uwsm app -- ~/.config/hypr/scripts/special-workspace-guard.sh
exec-once = hyprctl dispatch workspace 1
